name: Auto Assign Code Owners

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Assign Reviewers
        uses: armakuni/codeowners-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}